FROM python:3.13.4-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p data

WORKDIR /app/bot

CMD ["python3", "main_multi_network.py"]
